name: Check

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: pipeline-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Build with Pipeline
        uses: noobping/pipeline@continuous
        with:
          arguments: |
            --cap-jobs
            4
            build

      - name: Upload extension
        uses: actions/upload-artifact@v4
        with:
          name: category-sorted-app-grid
          path: dist/*.zip
          if-no-files-found: error
